version: '3'

services:

  nginx:
    build: nginx
    container_name: nginx
    networks:
      - doraemon
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    container_name: elasticsearch
    networks:
      - doraemon
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      
  redis:
    image: redis
    container_name: redis_cache
    networks:
      - doraemon
    ports:
      - "6379:6379"
      
  mysql:
    build: mysql
    container_name: mysql_db
    networks:
      - doraemon
    environment:
      MYSQL_ROOT_PASSWORD: iam_root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/world.sql:/docker-entrypoint-initdb.d/world.sql  #sample data set world
      - ./mysql/dd-agent.sql:/docker-entrypoint-initdb.d/dd-agent.sql 
      - ./mysql/ubuntu_helper.sql:/docker-entrypoint-initdb.d/ubuntu_helper.sql # Set up ubuntu helper
      
  postgres:
    build: postgres
    container_name: postgres
    networks:
      - doraemon
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/pgdduser.sql:/docker-entrypoint-initdb.d/pgdduser.sql # create dd user
      - ./postgres/dellstore2-normal-1.0.sql:/docker-entrypoint-initdb.d/dellstore2-normal-1.0.sql #sample
        
  datadog:
    build: datadog
    container_name: datadog_agent
    networks:
      - doraemon
    environment:
      - DD_API_KEY=
      - DD_HOSTNAME=
      - SD_BACKEND=docker
      - NON_LOCAL_TRAFFIC=false
      - ES_HOST=elasticsearch
      - DD_LOGS_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /opt/datadog-agent/conf.d:/conf.d:ro
      # - docker_logs.yaml:/conf.d/docker_logs.d/conf.yaml
      
  flask:
    build: flask
    container_name: flask
    networks:
      - doraemon
    ports:
      - "5000:5000"
      
  #Leverages siege in an ubuntu base container to ping a given web server (in this case it's NGINX)    
  ubuntu_siege:
    build: ubuntu_siege
    container_name: ubuntu_siege
    networks:
      - doraemon
  
  #Leverages MySQL client to query a given mysql server (SELECT only at the moment)   
  ubuntu_mysql:
    build: ubuntu_mysql
    container_name: ubuntu_mysql
    networks:
      - doraemon
      
# API Create Dash containers 
  api-helper:
    build: api-dash-creator
    container_name: api_dash_writer
    environment:
      - API_KEY=
      - APP_KEY=
      
networks:
  doraemon:
     driver: bridge
