# Example - MySQL
#
# Agent running a MySQL check

FROM datadog/docker-dd-agent

ADD mysql.yaml /etc/dd-agent/conf.d/mysql.yaml
ADD redisdb.yaml /etc/dd-agent/conf.d/redisdb.yaml
ADD postgres.yaml /etc/dd-agent/conf.d/postgres.yaml
ADD elastic.yaml /etc/dd-agent/conf.d/auto_conf/elastic.yaml
