FROM datadog/docker-dd-agent

ADD elastic.yaml /etc/dd-agent/conf.d/auto_conf/elastic.yaml
ADD mysql.yaml /etc/dd-agent/conf.d/mysql.yaml
ADD nginx.yaml /etc/dd-agent/conf.d/nginx.yaml
ADD redisdb.yaml /etc/dd-agent/conf.d/redisdb.yaml
ADD postgres.yaml /etc/dd-agent/conf.d/postgres.yaml
