import os
import random
import time

sql_queries = ['SELECT COUNT(*) FROM city;',
               'SELECT COUNT(*) FROM country;',
               'SELECT COUNT(*) FROM countrylanguage;',
               'DESC city;',
               'DESC country;',
               'DESC countrylanguage;',
               'SELECT * FROM city;',
               'SELECT * FROM country;',
               'SELECT * FROM countrylanguage;',
               'SELECT * FROM city WHERE Name LIKE \'A%\';',
               'SELECT * FROM city WHERE Name LIKE \'B%\';',
               'SELECT * FROM city WHERE Name LIKE \'C%\';',
               'SELECT * FROM city WHERE Name LIKE \'D%\';',
               'SELECT * FROM city WHERE Name LIKE \'E%\';',
               'SELECT * FROM city WHERE Name LIKE \'F%\';',
               'SELECT * FROM city WHERE Name LIKE \'G%\';',
               'SELECT * FROM city WHERE Name LIKE \'H%\';',
               'SELECT * FROM city WHERE Name LIKE \'I%\';',
               'SELECT * FROM city WHERE Name LIKE \'J%\';',
               'SELECT * FROM city WHERE Name LIKE \'K%\';',
               'SELECT * FROM city WHERE Name LIKE \'L%\';',
               'SELECT * FROM city WHERE Name LIKE \'M%\';',
               'SELECT * FROM city WHERE Name LIKE \'N%\';',
               'SELECT * FROM city WHERE Name LIKE \'O%\';',
               'SELECT * FROM city WHERE Name LIKE \'P%\';',
               'SELECT * FROM city WHERE Name LIKE \'Q%\';',
               'SELECT * FROM city WHERE Name LIKE \'R%\';',
               'SELECT * FROM city WHERE Name LIKE \'S%\';',
               'SELECT * FROM city WHERE Name LIKE \'T%\';',
               'SELECT * FROM city WHERE Name LIKE \'U%\';',
               'SELECT * FROM city WHERE Name LIKE \'V%\';',
               'SELECT * FROM city WHERE Name LIKE \'W%\';',
               'SELECT * FROM city WHERE Name LIKE \'X%\';',
               'SELECT * FROM city WHERE Name LIKE \'Y%\';',
               'SELECT * FROM city WHERE Name LIKE \'Z%\';',
               'SELECT * FROM country WHERE Name LIKE \'A%\';',
               'SELECT * FROM country WHERE Name LIKE \'B%\';',
               'SELECT * FROM country WHERE Name LIKE \'C%\';',
               'SELECT * FROM country WHERE Name LIKE \'D%\';',
               'SELECT * FROM country WHERE Name LIKE \'E%\';',
               'SELECT * FROM country WHERE Name LIKE \'F%\';',
               'SELECT * FROM country WHERE Name LIKE \'G%\';',
               'SELECT * FROM country WHERE Name LIKE \'H%\';',
               'SELECT * FROM country WHERE Name LIKE \'I%\';',
               'SELECT * FROM country WHERE Name LIKE \'J%\';',
               'SELECT * FROM country WHERE Name LIKE \'K%\';',
               'SELECT * FROM country WHERE Name LIKE \'L%\';',
               'SELECT * FROM country WHERE Name LIKE \'M%\';',
               'SELECT * FROM country WHERE Name LIKE \'N%\';',
               'SELECT * FROM country WHERE Name LIKE \'O%\';',
               'SELECT * FROM country WHERE Name LIKE \'P%\';',
               'SELECT * FROM country WHERE Name LIKE \'Q%\';',
               'SELECT * FROM country WHERE Name LIKE \'R%\';',
               'SELECT * FROM country WHERE Name LIKE \'S%\';',
               'SELECT * FROM country WHERE Name LIKE \'T%\';',
               'SELECT * FROM country WHERE Name LIKE \'U%\';',
               'SELECT * FROM country WHERE Name LIKE \'V%\';',
               'SELECT * FROM country WHERE Name LIKE \'W%\';',
               'SELECT * FROM country WHERE Name LIKE \'X%\';',
               'SELECT * FROM country WHERE Name LIKE \'Y%\';',
               'SELECT * FROM country WHERE Name LIKE \'Z%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'A%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'B%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'C%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'D%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'E%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'F%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'G%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'H%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'I%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'J%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'K%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'L%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'M%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'N%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'O%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'P%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'Q%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'R%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'S%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'T%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'U%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'V%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'W%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'X%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'Y%\';',
               'SELECT * FROM countrylanguage WHERE Language LIKE \'Z%\';'
               ]


#Run this in an infinite loop
while True:
    os.system("mysql -h mysql -u ubuntu -pubuntupass world --execute=\"" + sql_queries[random.randint(1, len(sql_queries)-1)] + "\"")
    wait_time = random.randint(1, 10)   #max wait time is 10 seconds
    time.sleep(wait_time)
    
